import { chmodSync } from 'node:fs';
import { join } from 'node:path';

import {
  SERVICE_LABEL,
  SERVICE_NAME,
  type ServiceContext,
  getServiceContext,
  shEscape,
  systemdEscape,
  toPosixPath,
  windowsCmdEscape,
  writeTextFile,
  xmlEscape,
} from './shared.ts';

export interface InstallOptions {
  /** Print generated artifacts but do not run any system command. */
  printOnly?: boolean;
  /** Install the service but do not start it immediately. */
  noStart?: boolean;
}

function logStep(message: string, details?: string): void {
  console.log(details ? `${message}\n${details}` : message);
}

async function runCommand(command: string[], cwd: string): Promise<void> {
  const proc = Bun.spawn(command, {
    cwd,
    stdin: 'ignore',
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Command failed (${code}): ${command.join(' ')}`);
  }
}

function buildWindowsRunner(ctx: ServiceContext): string {
  const logPath = join(ctx.serviceDir, 'supervisor.log');
  const cmdParts = [ctx.launch.bunPath, ...ctx.launch.args].map(windowsCmdEscape).join(' ');
  return [
    '@echo off',
    'chcp 65001 >nul',
    `cd /d ${windowsCmdEscape(ctx.launch.cwd)}`,
    `${cmdParts} >> ${windowsCmdEscape(logPath)} 2>&1`,
  ].join('\r\n');
}

function psSingleQuote(input: string): string {
  return `'${input.replaceAll("'", "''")}'`;
}

function buildWindowsHiddenRunner(ctx: ServiceContext): string {
  const logPath = join(ctx.serviceDir, 'supervisor.log');
  const command = [ctx.launch.bunPath, ...ctx.launch.args].map(psSingleQuote).join(' ');
  return [
    "$ErrorActionPreference = 'Stop'",
    `Set-Location -LiteralPath ${psSingleQuote(ctx.launch.cwd)}`,
    `& ${command} *>> ${psSingleQuote(logPath)}`,
  ].join('\r\n');
}

/**
 * VBScript wrapper that invokes the PowerShell runner with SW_HIDE.
 *
 * Why VBS instead of `powershell.exe -WindowStyle Hidden` directly:
 *   When Task Scheduler launches a console-subsystem process (powershell.exe)
 *   interactively, Windows allocates a conhost window BEFORE PowerShell can
 *   hide it, causing a visible console window. wscript.exe is a GUI-subsystem
 *   process with no console of its own, and `WshShell.Run cmd, 0` starts the
 *   child with SW_HIDE — so no console window ever appears.
 */
function vbsQuote(input: string): string {
  return `"${input.replaceAll('"', '""')}"`;
}

function buildWindowsVbsLauncher(hiddenRunnerPath: string): string {
  // Build:  powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "<ps1>"
  // Then run via WshShell.Run with intWindowStyle = 0 (SW_HIDE), bWaitOnReturn = False.
  const psCommand =
    `""powershell.exe"" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ""${hiddenRunnerPath.replaceAll('"', '""')}""`;
  return [
    "' Auto-generated by sessions-ai service install. Runs the supervisor with no visible window.",
    'Set objShell = CreateObject("WScript.Shell")',
    `objShell.Run "${psCommand}", 0, False`,
  ].join('\r\n');
}

function buildWindowsTaskCommand(vbsLauncherPath: string): string {
  return `${windowsCmdEscape('wscript.exe')} ${windowsCmdEscape(vbsLauncherPath)}`;
}

async function installWindows(ctx: ServiceContext, opts: InstallOptions): Promise<void> {
  const cmdRunnerPath = join(ctx.serviceDir, 'run-supervisor.cmd');
  const hiddenRunnerPath = join(ctx.serviceDir, 'run-supervisor.ps1');
  const vbsLauncherPath = join(ctx.serviceDir, 'run-supervisor.vbs');
  const cmdRunner = buildWindowsRunner(ctx);
  const hiddenRunner = buildWindowsHiddenRunner(ctx);
  const vbsLauncher = buildWindowsVbsLauncher(hiddenRunnerPath);
  const taskCommand = buildWindowsTaskCommand(vbsLauncherPath);

  writeTextFile(cmdRunnerPath, `${cmdRunner}\r\n`);
  writeTextFile(hiddenRunnerPath, `${hiddenRunner}\r\n`);
  writeTextFile(vbsLauncherPath, `${vbsLauncher}\r\n`);

  if (opts.printOnly) {
    logStep('Windows Task Scheduler wrapper preview (cmd, manual debug):', cmdRunnerPath);
    logStep(cmdRunner);
    logStep('Windows Task Scheduler wrapper preview (hidden ps1):', hiddenRunnerPath);
    logStep(hiddenRunner);
    logStep('Windows Task Scheduler wrapper preview (vbs, no-console launcher):', vbsLauncherPath);
    logStep(vbsLauncher);
    logStep('Windows Task Scheduler command preview:', taskCommand);
    return;
  }

  await runCommand(
    ['schtasks', '/Create', '/TN', SERVICE_NAME, '/SC', 'ONLOGON', '/F', '/TR', taskCommand],
    ctx.launch.cwd,
  );

  if (!opts.noStart) {
    await runCommand(['schtasks', '/Run', '/TN', SERVICE_NAME], ctx.launch.cwd);
  }

  logStep(
    'Windows persistent task installed.',
    `Task: ${SERVICE_NAME}\nTask Command: ${taskCommand}\nLauncher (no console): ${vbsLauncherPath}\nPS1 Wrapper: ${hiddenRunnerPath}\nLegacy CMD Wrapper (manual debug): ${cmdRunnerPath}\nLog: ${join(ctx.serviceDir, 'supervisor.log')}`,
  );
}

function buildLaunchAgent(ctx: ServiceContext): string {
  const stdoutPath = xmlEscape(join(ctx.serviceDir, 'stdout.log'));
  const stderrPath = xmlEscape(join(ctx.serviceDir, 'stderr.log'));
  const programArgs = [ctx.launch.bunPath, ...ctx.launch.args]
    .map((p) => `      <string>${xmlEscape(p)}</string>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>${SERVICE_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
${programArgs}
    </array>
    <key>WorkingDirectory</key>
    <string>${xmlEscape(ctx.launch.cwd)}</string>
    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>${xmlEscape(ctx.pathEnv)}</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${stdoutPath}</string>
    <key>StandardErrorPath</key>
    <string>${stderrPath}</string>
  </dict>
</plist>
`;
}

async function installMac(ctx: ServiceContext, opts: InstallOptions): Promise<void> {
  const plistPath = join(ctx.homeDir, 'Library', 'LaunchAgents', `${SERVICE_LABEL}.plist`);
  const content = buildLaunchAgent(ctx);
  writeTextFile(plistPath, content);

  if (opts.printOnly) {
    logStep('macOS launchd plist preview:', plistPath);
    logStep(content);
    return;
  }

  if (opts.noStart) {
    logStep(
      'macOS LaunchAgent plist written but not loaded (--no-start).',
      `plist: ${plistPath}\nTo activate later: launchctl load -w ${plistPath}`,
    );
    return;
  }

  await runCommand(['launchctl', 'unload', plistPath], ctx.launch.cwd).catch(() => undefined);
  await runCommand(['launchctl', 'load', '-w', plistPath], ctx.launch.cwd);

  logStep(
    'macOS LaunchAgent installed.',
    `plist: ${plistPath}\nstdout: ${join(ctx.serviceDir, 'stdout.log')}\nstderr: ${join(ctx.serviceDir, 'stderr.log')}`,
  );
}

function buildLinuxRunner(ctx: ServiceContext): string {
  const escaped = [ctx.launch.bunPath, ...ctx.launch.args].map(shEscape).join(' ');
  return [
    '#!/usr/bin/env sh',
    'set -eu',
    `cd ${shEscape(ctx.launch.cwd)}`,
    `exec ${escaped}`,
  ].join('\n');
}

function buildSystemdUnit(ctx: ServiceContext, runnerPath: string): string {
  return `[Unit]
Description=sessions-ai Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${systemdEscape(ctx.launch.cwd)}
ExecStart=${systemdEscape(runnerPath)}
Restart=always
RestartSec=5
Environment=PATH=${systemdEscape(ctx.pathEnv)}

[Install]
WantedBy=default.target
`;
}

async function installLinux(ctx: ServiceContext, opts: InstallOptions): Promise<void> {
  const runnerPath = join(ctx.serviceDir, 'run-supervisor.sh');
  const runnerContent = buildLinuxRunner(ctx);
  writeTextFile(runnerPath, `${runnerContent}\n`);
  chmodSync(runnerPath, 0o755);

  const unitPath = join(ctx.homeDir, '.config', 'systemd', 'user', `${SERVICE_NAME}.service`);
  const unitContent = buildSystemdUnit(ctx, runnerPath);
  writeTextFile(unitPath, unitContent);

  if (opts.printOnly) {
    logStep('Linux systemd user service preview:', unitPath);
    logStep(unitContent);
    return;
  }

  if (opts.noStart) {
    logStep(
      'Linux systemd user unit written but not started (--no-start).',
      `unit: ${unitPath}\nrunner: ${runnerPath}\nTo activate later: systemctl --user daemon-reload && systemctl --user enable --now ${SERVICE_NAME}.service`,
    );
    return;
  }

  await runCommand(['systemctl', '--user', 'daemon-reload'], ctx.launch.cwd);
  await runCommand(['systemctl', '--user', 'enable', '--now', `${SERVICE_NAME}.service`], ctx.launch.cwd);

  logStep(
    'Linux systemd user service installed.',
    `unit: ${unitPath}\nrunner: ${runnerPath}\nTo keep running after logout, run: loginctl enable-linger ${process.env.USER ?? '$USER'}`,
  );
}

export async function installService(opts: InstallOptions = {}): Promise<void> {
  const ctx = getServiceContext();
  logStep(
    'Preparing to install persistent Agent service.',
    `Platform: ${process.platform}\nWorking directory: ${toPosixPath(ctx.launch.cwd)}\nLaunch: ${[ctx.launch.bunPath, ...ctx.launch.args].join(' ')}`,
  );

  switch (process.platform) {
    case 'win32':
      await installWindows(ctx, opts);
      return;
    case 'darwin':
      await installMac(ctx, opts);
      return;
    default:
      await installLinux(ctx, opts);
  }
}
